### ISSUE TITLE
Using Search vs GDS

### ISSUE THREAD

**Issue by emilorol** [tomwalder/php-appengine-search#13]
Hi Tom,

Quick question: is there any way I could use your two libraries at once?

Since the document creation is so close to the regular entity creation on GDS, how can I utilize both so that my entities go to the datastore and be searchable at once

**Comment by tomwalder** [comment]
Hi there,

I am sure you could build a layer of software to do this - the two
libraries are currently not linked together.

Tom

On 10 May 2016 at 20:17, Emil Orol notifications@github.com wrote:

> Hi Tom,
> 
> Quick question: is there any way I could use your two libraries at once?
> 
> Since the document creation is so close to the regular entity creation on
> GDS, how can I utilize both so that my entities go to the datastore and be
> searchable at once
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/tomwalder/php-appengine-search/issues/13

## 

_Tom Walder_, CTO
_We're hiring._ Find out more at www.docnet.nu/jobs
http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature
_Call_: 0161 660 7110 / _Web_: www.docnet.nu
http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature
This message is private and confidential. If you have received this message
in error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by emilorol** [comment]
Hi Tom,

Thank you for your quick answer. Those this mean that if I want to use the entities I have on GDS with the Search at creation or update time I also have to create an document for them so that they can be search?

**Comment by emilorol** [comment]
Seems like this is a common question:

http://stackoverflow.com/questions/10951936/when-should-i-not-use-app-engines-full-text-search-api

http://stackoverflow.com/questions/23317280/appengine-search-api-vs-datastore

And the solution will seem to be use the datastore to keep your entities and the search API to retrieve their content using a full text search.

http://sookocheff.com/post/appengine/syncing-search-documents-with-datastore-entities/

**Comment by tomwalder** [comment]
Hey Emil.

Thanks for the post.

Tom
