### ISSUE TITLE
Get document by id bug

### ISSUE THREAD

**Issue by stubbies** [tomwalder/php-appengine-search#8]
I'm trying to validate if a document exists by using `$obj_index->get('test-123');` but if that document doesn't exists it returns the last added one.

Is this a bug or is this what it's supposed to do?

**Comment by tomwalder** [comment]
Doesn't sound right... I'll look into it.

Is this on the local development server or on App Engine?

**Comment by tomwalder** [comment]
Just looked at the code. It's a bug.

I'll drop a fix in place shortly.

**Comment by stubbies** [comment]
Thanks
